Initial Yelp library structure
neighborhoods/Yelp-Fusion pull request #1
Opened 2017-09-26 18:25 UTC by rteague

2017-09-26 19:05 UTC, MattStypa requested changes

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> + * @package Neighborhoods\Libraries
Wrong namespace. `Neighborhoods\YelpFusion`

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> +namespace Neighborhoods\Libraries;
Neighborhoods\YelpFusion

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> +     * @param null $handler
Needs more information about this

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> +     * @return mixed
This returns an object

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> +     * @return mixed
Object

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> +     */
Missing @throws

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> +     */
Missing @throws

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> +     * @return mixed
Object

2017-09-26 19:05 UTC, MattStypa commented on src/Yelp.php
> +     * Get the bearer token
'Gets the bearer token'

2017-09-26 19:05 UTC, MattStypa commented on tests/YelpTest.php
> + * @package  YelpTest
Shouldn't this be `Yelp`

2017-09-26 19:05 UTC, MattStypa commented on composer.json
> +{
This file has mixed indentation. Tabs+Spaces

2017-09-26 19:05 UTC, MattStypa commented on phpunit.xml
> +<phpunit 	bootstrap="vendor/autoload.php"
Please use space indentation and align the properties better

2017-09-26 19:05 UTC, MattStypa commented on phpunit.xml
> +			</testsuites>
Missing whitelist configuration

2017-09-26 20:12 UTC, rteague commented on src/Yelp.php
> +     */
But this doesn't throw anything.

2017-09-26 20:31 UTC, MattStypa commented on src/Yelp.php
> +     */
It calls two separate methods that throw so this throws as well.

2017-09-26 20:36 UTC, MattStypa requested changes

2017-09-26 20:36 UTC, MattStypa commented on src/Yelp.php
> + * @package  Yelp
`Neighborhoods\YelpFusion`

2017-09-26 20:36 UTC, MattStypa commented on src/Yelp.php
> +     */
@throws

2017-09-26 20:36 UTC, MattStypa commented on src/Yelp.php
> +     */
@throws

2017-09-26 20:36 UTC, MattStypa commented on tests/YelpTest.php
> + * @package  Yelp
Neighborhoods\YelpFusion

2017-09-26 20:36 UTC, MattStypa commented on composer.json
> +      "Neighborhoods\\": "src/"
"Neighborhoods\\YelpFusion\\": "src/"

2017-09-26 20:38 UTC, MattStypa requested changes

2017-09-26 20:38 UTC, MattStypa commented on tests/YelpTest.php
> +namespace Neighborhoods\Tests\YelpFusion;
Neighborhoods\YelpFusion\tests;

2017-09-26 20:49 UTC, jpmarcotte commented on src/Yelp.php
> +     */
This will probably be helpful: https://blog.jetbrains.com/phpstorm/2016/07/docblock-improvements-for-throws-in-phpstorm-2016-2/

2017-09-27 13:35 UTC, MattStypa approved these changes

2017-09-27 14:40 UTC, merged